version: "2"
services: 
    proxy:
        image: httpd
        depends_on: 
          - web
    web:
        image: node:8.12-jessie
        ports: 
          - "8080:80"
        depends_on: 
          - db
    db:
        image: redis
        ports: 
          - "6379:6379"