version: "2"
services:
    php:
        image: php
        ports: 
          - "80:80"
        depends_on:
          - "db"
    db:
        image: microsoft/mssql-server-linux
        environment: 
          SA_PASSWORD: "Your_password123"
          ACCEPT_EULA: "Y"